### ISSUE TITLE
Color precision can be lost from GdkRGBA

### ISSUE THREAD

**Issue by chergert** [lainsce/colorway#21]
https://github.com/lainsce/colorway/blob/6001f778371b55c414e1b438d3aac17005be4ea0/src/utils.vala#L21

I happened across this earlier when I was working on some color palette things, and I made the same mistake in some of my code. This needs to use `roundf()` instead of always dropping the precision.

Test case: `#6362C8`

**Comment by lainsce** [comment]
`roundf()` around each uint? :thinking:

**Comment by chergert** [comment]
Correct otherwise when the integer value is converted to a floating point you might get something with .7 rounding down to .0 as an integer when the original value was greater.

Just part of life when using floating point for colors like GdkRGBA does.

**Comment by lainsce** [comment]
I see! OK, will do the changes soon. :)
