### ISSUE TITLE
[Bug] Hue slider has incorrect rainbow direction

### ISSUE THREAD

**Issue by tkrill** [lainsce/colorway#27]
Running the flatpak version of Colorway 1.1.1 i have problems selecting colors. (Or i just don't understand how it works)

Lets say i want to select the color yellow. I position the slider to the right above yellow and then try to find the correct color in the selection area to the left.

![image](https://user-images.githubusercontent.com/4834534/164377253-e180361f-29f8-4ced-90bc-a751e6744662.png)

I'm however unable to select or find this color. The same problem also seems present in the screenshot referenced in the main README.md with [this image](https://github.com/lainsce/colorway/tree/main/data/shot.png)

**Comment by lainsce** [comment]
Oh whoops, forgot to make the rainbow on the slider match the hue... It's inverted vertically. Will fix.

**Comment by lainsce** [comment]
Fixed, will be on next release.
