### ISSUE TITLE
Very long launch time ( about 20 seconds )

### ISSUE THREAD

**Issue by lumingzh** [lainsce/colorway#29]
- OS: Fedora Silverblue 35
- DE: Gnome Shell 41
- Flatpak: 1.12.7
- Colorway: 1.2.0

Here is the first launch debug message:

> F: No installations directory in /etc/flatpak/installations.d. Skipping
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: Opening user flatpak installation at path /var/home/lumingzh/.local/share/flatpak
> F: Opening user flatpak installation at path /var/home/lumingzh/.local/share/flatpak
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: Opening user flatpak installation at path /var/home/lumingzh/.local/share/flatpak
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/42/d240597586ac4c87e7e8dd634b67a3c910704b77d1ef5927147e55fe57cf569a/files/lib32 does not exist
> F: Allocated instance id 748832608
> F: Add defaults in dir /io/github/lainsce/Colorway/
> F: Add locks in dir /io/github/lainsce/Colorway/
> F: Disallowing network access
> F: Allowing dri access
> F: Allowing wayland access
> F: Running 'bwrap --args 37 xdg-dbus-proxy --args=40'
> F: Running 'bwrap --args 37 io.github.lainsce.Colorway'

Here is the second launch debug message:

> F: No installations directory in /etc/flatpak/installations.d. Skipping
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: Opening user flatpak installation at path /var/home/lumingzh/.local/share/flatpak
> F: Opening user flatpak installation at path /var/home/lumingzh/.local/share/flatpak
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: Opening user flatpak installation at path /var/home/lumingzh/.local/share/flatpak
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/42/d240597586ac4c87e7e8dd634b67a3c910704b77d1ef5927147e55fe57cf569a/files/lib32 does not exist
> F: Cleaning up unused container id 748832608
> F: Cleaning up per-app-ID state for io.github.lainsce.Colorway
> F: Allocated instance id 2313050806
> F: Add defaults in dir /io/github/lainsce/Colorway/
> F: Add locks in dir /io/github/lainsce/Colorway/
> F: Disallowing network access
> F: Allowing dri access
> F: Allowing wayland access
> F: Running 'bwrap --args 37 xdg-dbus-proxy --args=40'
> F: Running 'bwrap --args 37 io.github.lainsce.Colorway'

**Comment by lainsce** [comment]
I'm not sure how to fix this, honestly.

**Comment by lumingzh** [comment]
Yes, I tested other flatpak apps and the debug messages are same. Don't know why Colorway launch so slow.

**Comment by lumingzh** [comment]
> Yes, I tested other flatpak apps and the debug messages are same. Don't know why Colorway launch so slow.

And it launched very fast before, the change happened recently.

**Comment by lainsce** [comment]
Then something happened outside of my app, because the code is the same as the fast version.
