### ISSUE TITLE
Graphical glitch with copy colour button

### ISSUE THREAD

**Issue by kdwk** [lainsce/colorway#8]
## Hello! If you found an error in this app, follow this template:

https://user-images.githubusercontent.com/39268094/143673662-110f4cbc-ed64-4309-88c5-e5378c7239dc.mp4

The copy colour button flashes continuously. 

io.github.lainsce.Colorway 1.0.2

Gnome 41, Wayland, Fedora 35

**Comment by lainsce** [comment]
Fixed in the repo, will come to next release. :)
